[package]
name = "pallet-openinfra-rewards"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
codec = { workspace = true }
frame-support = { version = "48.0.0", default-features = false }
frame-system = { version = "48.0.0", default-features = false }
scale-info = { workspace = true }

[dev-dependencies]
sp-io = { version = "48.0.0" }
sp-runtime = { version = "48.0.0" }

[features]
default = ["std"]
runtime-benchmarks = []
std = ["codec/std", "frame-support/std", "frame-system/std", "scale-info/std"]
